function onscreen(e,m=45){let x=e.x-G.camX,y=e.y-G.camY;return x>-m&&x<G.w+m&&y>45-m&&y<G.h+m}
function fart(e){e.fartA=.32;G.rainbows.push({x:e.x-e.face*65,y:e.y+20,s:e.boss?1:.82,a:1,life:30,hit:0,f:e.face,c:0});sfx('fart')}
function kill(e){e.hp=0;e.dead=.01;e.warn=0;sfx('dead');if(G.target===e){G.target=null;G.attackHold=0}}
function startAbility(e,ci){let P=G.player;if(ci!==3&&!onscreen(e,0))return;e.kind=ci;e.warn=ci===4?.58:ci===5?.42:ci<2?.32:.46;if(ci===3)e.ally=G.enemies.find(x=>!x.dead&&x!==e&&x.hp<x.max)||0;if(ci===5){let a=Math.random()*7;e.wx=clamp(P.x+Math.cos(a)*230,70,G.worldW-70);e.wy=clamp(P.y+Math.sin(a)*180,G.groundTop,G.worldH-70)}sfx('warn')}
function resolveAbility(e){let P=G.player,k=e.kind,d=Math.hypot(P.x-e.x,P.y-e.y);if(k<2){if(d<(k?125:105))hitBeauty(k?8:7)}else if(k===2){if(d<205)hitBeauty(8)}else if(k===3){if(e.ally&&!e.ally.dead)e.ally.hp=Math.min(e.ally.max,e.ally.hp+28)}else if(k===4){let dx=P.x-e.x,dy=P.y-e.y,m=Math.hypot(dx,dy)||1,dot=(dx*(e.tx||dx)+dy*(e.ty||dy))/(m*(Math.hypot(e.tx||dx,e.ty||dy)||1));if(d<270&&dot>.94)hitBeauty(10)}else if(k===5){e.x=e.wx;e.y=e.wy;fart(e)}e.kind=-1}
function ability(e,dt){if(G.black)return;if(e.warn>0){e.warn-=dt;if(e.kind===4&&!e.tx){e.tx=G.player.x-e.x;e.ty=G.player.y-e.y}if(e.warn<=0){resolveAbility(e);e.tx=e.ty=0}return}e.act-=dt;if(e.act>0)return;e.act=1.5+Math.random()*1.5;let ci=e.ci;if(e.boss===3){ci=Math.max(0,Math.ceil(e.hp/e.max*7)-1);e.ci=ci;e.col=COLORS[ci]}if(ci===6)ci=Math.random()*6|0;startAbility(e,ci)}
function steer(e,dt){if(e.dead)return;let P=G.player,dx=P.x-e.x,dy=P.y-e.y,d=Math.hypot(dx,dy)||1,nx=dx/d,ny=dy/d,ci=e.ci,tx=0,ty=0,sp=e.boss?42:ci===1?74:48;if(e.warn>0&&(e.kind===2||e.kind===4))sp*=.25;if(ci===0){tx=nx;ty=ny}else if(ci===1){tx=-ny*.9+nx*.35;ty=nx*.9+ny*.35}else if(ci===2){let q=d>270?1:d<190?-1:0;tx=nx*q;ty=ny*q}else if(ci===3){let a=G.enemies.find(x=>!x.dead&&x!==e&&x.hp<x.max);if(a){let ax=a.x-e.x,ay=a.y-e.y,m=Math.hypot(ax,ay)||1;tx=ax/m;ty=ay/m}else{tx=-ny*.5;ty=nx*.5}}else if(ci===4){let q=d>330?1:d<250?-1:0;tx=nx*q;ty=ny*q}else if(ci===5){tx=-ny*.7;ty=nx*.7}else{tx=nx*.25-ny*.5;ty=ny*.25+nx*.5}e.face=Math.abs(tx)>.08?(tx<0?-1:1):(dx<0?-1:1);e.x=clamp(e.x+tx*sp*dt,65,G.worldW-65);e.y=clamp(e.y+ty*sp*dt,G.groundTop,G.worldH-65);let px=e.x-P.x,py=e.y-P.y,pd=Math.hypot(px,py)||1;if(pd<92){e.x=P.x+px/pd*92;e.y=P.y+py/pd*92}}
function separate(){for(let i=0;i<G.enemies.length;i++)for(let j=i+1;j<G.enemies.length;j++){let a=G.enemies[i],b=G.enemies[j];if(a.dead||b.dead)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,m=(a.boss||b.boss?96:88)-d;if(m>0){let q=m*.5/d;a.x-=dx*q;a.y-=dy*q;b.x+=dx*q;b.y+=dy*q}}}
function lockTarget(ax,ay,R=220){let P=G.player,best=null,bd=1e9;for(let e of G.enemies)if(!e.dead){let dx=e.x-P.x,dy=e.y-P.y,d=Math.hypot(dx,dy),dot=(dx*ax+dy*ay)/(d||1),td=Math.hypot(Input.ax-(e.x-G.camX),Input.ay-(e.y-G.camY)),m=td<105?td:d;if(d<R&&(dot>.55||td<105)&&m<bd){best=e;bd=m}}return best}
function combatStep(dt){let P=G.player,[ax,ay]=aimIntent(P);G.aimX=ax;G.aimY=ay;if(Input.attack)P.face=ax<0?-1:1;if(G.waitRelease){if(!Input.attack)G.waitRelease=0;return}if(Input.attackPressed){G.attackTime=0;G.attackHadTarget=0;if(Input.ay<55&&Input.ax>G.w*.5){blackout();G.attackHadTarget=1;return}}if(Input.attack){G.attackTime+=dt;if(G.target&&!G.target.dead&&Math.hypot(G.target.x-P.x,G.target.y-P.y)>260)G.target=null;G.hover=G.target||lockTarget(ax,ay);if(G.attackTime>.2&&!G.target&&G.hover){G.target=G.hover;G.attackHold=G.attackHadTarget=1;sfx('absorb')}}
 if(Input.attackReleased){let held=G.attackHadTarget,q=G.hover||lockTarget(ax,ay,440);G.target=G.hover=null;G.attackHold=0;G.attackHadTarget=G.attackTime=0;if(!held&&Input.ay>55){if(q){let dx=q.x-P.x,dy=q.y-P.y,m=Math.hypot(dx,dy)||1;ax=dx/m;ay=dy/m;P.face=ax<0?-1:1}let p=1+Math.max(0,G.beauty-40)/45;G.shots.push({x:P.x+P.face*27,y:P.y-28,vx:ax*340,vy:ay*340,p});sfx('shot')}}
 if(G.target&&!G.target.dead){let m=G.black?2.7:Math.max(.55,1-G.beauty*.004);G.target.hp-=CFG.absorb*100*dt*m;G.void=Math.min(100,G.void+14*dt);if(Math.random()<dt*4)sfx('drain');if(G.target.hp<=0)kill(G.target)}
 for(let e of G.enemies){if(e.dead){e.dead+=dt;e.y-=12*dt;continue}steer(e,dt);e.fart-=dt;if(e.fart<=0){if(onscreen(e,80))fart(e);e.fart=(e.ci===1?4:7)+Math.random()*(e.ci===1?2:3)-(e.boss?.4:0)}ability(e,dt)}separate();
 for(let s of G.shots){s.x+=s.vx*dt;s.y+=s.vy*dt;for(let e of G.enemies)if(!e.dead&&Math.hypot(s.x-e.x,s.y-e.y)<CFG.enemyR+(e.boss?20:0)){e.hp-=CFG.shot*s.p;e.hit=.18;s.y=-999;if(e.hp<=0)kill(e)}}G.shots=G.shots.filter(s=>s.y>G.groundTop-120&&s.y<G.worldH+80&&s.x>-50&&s.x<G.worldW+50);
 for(let r of G.rainbows){r.life-=dt;r.a=Math.min(1,r.life);if(!r.land&&r.life<29.66){r.land=1;sfx('splat')}if(r.life<29.66&&!r.hit&&Math.hypot(P.x-r.x,P.y-r.y)<42){r.hit=1;hitBeauty(CFG.beautyHit)}}G.rainbows=G.rainbows.filter(r=>r.life>0);if(G.enemies.length&&G.enemies.every(e=>e.dead))finishEncounter()}
