const C=document.querySelector('canvas'),ctx=C.getContext('2d');let DPR=1,last=0;
const G=window.GAME={phase:'intro',introStep:0,introLine:'Peace. Quiet. Dead flowers.',beauty:0,void:0,run:0,zone:0,boss:0,msg:0,msgText:'',black:0,camX:0,camY:0,worldW:0,worldH:0,hor:290,groundTop:375,w:390,h:780,player:{x:164,y:650,beauty:0,face:1},enemies:[],rainbows:[],shots:[],target:null,hover:null,attackHold:0,attackHadTarget:0,attackTime:0,aimX:1,aimY:0,cleanReady:0,waitRelease:0,dmv:0,endStep:0};
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function size(){DPR=Math.min(2,devicePixelRatio||1);let iw=typeof innerWidth!='undefined'?innerWidth:390,ih=typeof innerHeight!='undefined'?innerHeight:780,wide=iw>ih&&typeof matchMedia!='undefined'&&matchMedia('(pointer:fine)').matches;G.w=wide?640:520;G.h=wide?780:Math.round(520*ih/iw);C.width=Math.round(G.w*DPR);C.height=Math.round(G.h*DPR);let cw=wide?Math.min(iw,ih*G.w/G.h):iw,ch=wide?cw*G.h/G.w:ih;if(C.style){C.style.width=cw+'px';C.style.height=ch+'px'}ctx.setTransform(DPR,0,0,DPR,0,0);G.hor=Math.round(G.h*.372);G.groundTop=G.hor+Math.round(G.h*.109);G.worldW=Math.max(G.worldW||0,G.w*2.55);G.worldH=Math.max(G.worldH||0,G.h*1.35);G.player.x=clamp(G.player.x,55,G.worldW-55);G.player.y=clamp(G.player.y,G.groundTop,G.worldH-70);G.camX=clamp(G.camX,0,G.worldW-G.w);G.camY=clamp(G.camY,0,G.worldH-G.h)}
function say(s,n=2.1){G.msgText=s;G.msg=n}
function enemy(ci,x,y,boss=0){let hp=boss?boss===3?650:430:100;return{x,y,hp,max:hp,col:COLORS[ci],fart:4.5+Math.random()*2.5,fartA:0,hit:0,act:1+Math.random(),ci,dead:0,boss,face:-1,warn:0,kind:-1}}
function spawn(){let q=SEQ[G.run];if(!q)return ending();G.phase='fight';G.waitRelease=Input.attack?1:0;G.attackHadTarget=0;G.enemies=[];G.boss=0;G.rainbows=[];G.shots=[];G.zone=G.run<3?0:G.run<6?1:2;let k=G.run%3;if(!k){G.worldW=G.w*2.55;G.worldH=G.h*1.35;G.camX=G.camY=0;G.player.x=G.w*.42;G.player.y=G.groundTop+270}let cx=G.w*(.72+k*.73),fy=G.groundTop+145+(k%2)*105;if(typeof q[0]==='string'){let b=q[0]==='S'?1:q[0]==='P'?2:3,ci=b===1?2:6;G.boss=b;G.enemies=[enemy(ci,cx,fy+35,b)];say(q[1]+': '+q[2],3);sfx('warn')}else{let a=q[0],n=a.length;for(let i=0;i<n;i++)G.enemies.push(enemy(a[i],cx+(i-(n-1)/2)*118,fy+(i%2)*115));say(q[1])}}
function reset(){G.beauty=G.player.beauty=G.void=G.run=G.black=G.endStep=0;G.rainbows=[];G.shots=[];G.worldW=G.worldH=0;size();spawn()}
function hitBeauty(n){if(G.black||G.player.hit>0)return;G.player.hit=.22;G.beauty=Math.min(100,G.beauty+n);G.player.beauty=G.beauty;sfx('hit');if(G.beauty>=100)G.phase='over';else if(G.beauty>80&&G.beauty-n<=80)say('This is offensively powerful.');else if(G.beauty>65&&G.beauty-n<=65)say('WHY IS MY MANE SO SOFT?');else if(G.beauty>30&&G.beauty-n<=30)say('Absolutely not.')}
function blackout(){if(G.void<100||G.black)return;G.void=0;G.black=1.8;G.target=null;G.attackHold=0;sfx('black');say('BLACKOUT.',1.2)}
function step(dt){if(G.msg>0)G.msg-=dt;if(G.player.hit>0)G.player.hit-=dt;for(let e of G.enemies){if(e.hit>0)e.hit-=dt;if(e.fartA>0)e.fartA-=dt}if(G.black>0){G.black-=dt;for(let e of G.enemies)if(!e.dead){e.hp-=22*dt;if(e.hp<=0)kill(e)}}if(G.phase==='intro'){if(Input.pressed){audioInit();G.introStep++;if(G.introStep===1){G.introLine='PRRRRRT.';sfx('fart')}else if(G.introStep===2)G.introLine='...again.';else reset()}return}if(G.phase==='over'){if(Input.pressed){G.phase='intro';G.introStep=0;G.introLine='Peace. Quiet. Dead flowers.'}return}if(G.phase==='ending'){if(Input.pressed){G.endStep++;if(G.endStep>2){G.phase='intro';G.introStep=0;G.introLine='Peace. Quiet. Dead flowers.'}}return}if(G.phase==='fight')fight(dt);else if(G.phase==='clean')clean(dt);else if(G.phase==='dmv')dmv(dt)}
function follow(dt){let P=G.player,T=G.target,dx=G.camX,dy=G.camY;if(T){dx=(P.x+T.x-G.w)/2+(T.x-P.x)*.08;dy=(P.y+T.y-G.h)/2}else{let l=G.camX+G.w*.34,r=G.camX+G.w*.66,u=G.camY+G.h*.38,d=G.camY+G.h*.68;if(P.x<l)dx=P.x-G.w*.34;else if(P.x>r)dx=P.x-G.w*.66;if(P.y<u)dy=P.y-G.h*.38;else if(P.y>d)dy=P.y-G.h*.68}dx=clamp(dx,0,G.worldW-G.w);dy=clamp(dy,0,G.worldH-G.h);let k=Math.min(1,dt*7);G.camX+=(dx-G.camX)*k;G.camY+=(dy-G.camY)*k}
function fight(dt){if(Input.black){blackout();Input.black=0}let P=G.player,[mx,my]=moveIntent(),sp=190*(1+G.beauty*.003)*(G.target?.8:1);P.x=clamp(P.x+mx*sp*dt,55,G.worldW-55);P.y=clamp(P.y+my*sp*dt,G.groundTop,G.worldH-70);if(!Input.attack&&Math.abs(mx)>.15)P.face=mx<0?-1:1;follow(dt);combatStep(dt)}
function finishEncounter(){let boss=G.boss;G.target=G.hover=null;G.attackHold=0;G.attackHadTarget=G.attackTime=0;G.enemies=[];G.msg=0;if(boss===3)return ending();if(boss===2){G.phase='dmv';G.dmv=4.5;G.rainbows=[];sfx('dmv');return}G.phase='clean';G.cleanReady=0;G.rainbows=G.rainbows.filter(r=>r.x>G.camX+35&&r.x<G.camX+G.w-35&&r.y>G.camY+70&&r.y<G.camY+G.h-35)}
function next(){G.run++;spawn()}
function clean(dt){if(!G.cleanReady){if(!Input.down)G.cleanReady=1;return}for(let r of G.rainbows)if(r.c){r.c+=dt*6;if(r.c>=1)r.life=0}if(Input.down){let ix=Input.x+G.camX,iy=Input.y+G.camY;for(let r of G.rainbows)if(!r.c&&r.life>0&&Math.hypot(ix-r.x,iy-r.y)<58){r.c=.01;G.beauty=Math.max(0,G.beauty-CFG.clean);G.player.beauty=G.beauty;sfx('clean')}}G.rainbows=G.rainbows.filter(r=>r.life>0);if(!G.rainbows.length){G.beauty=Math.max(0,G.beauty-38*dt);G.player.beauty=G.beauty;if(G.beauty<=1)next()}}
function dmv(dt){G.dmv-=dt;G.beauty=Math.max(0,G.beauty-25*dt);G.player.beauty=G.beauty;if(G.dmv<=0)next()}
function ending(){G.phase='ending';G.endStep=0;G.boss=0;G.rainbows=[];sfx('win')}
function loop(t){let dt=Math.min(.05,(t-last)/1000||0);last=t;step(dt);render(G);Input.pressed=Input.released=Input.attackPressed=Input.attackReleased=0;requestAnimationFrame(loop)}
addEventListener('resize',size);bindInput(C);size();C.focus?.();requestAnimationFrame(loop);
