const Input={x:0,y:0,down:0,pressed:0,released:0,moveId:-1,attackId:-1,moX:0,moY:0,mx:0,my:0,ax:390,ay:390,aoX:0,aoY:0,attack:0,attackPressed:0,attackReleased:0,mouse:0,keys:{},pts:{},black:0};
function bindInput(c){
 const pos=e=>{let r=c.getBoundingClientRect();return[(e.clientX-r.left)*G.w/r.width,(e.clientY-r.top)*G.h/r.height]},clear=()=>{let a=Input.attack;Input.keys={};Input.pts={};Input.moveId=Input.attackId=-1;Input.down=Input.attack=0;Input.attackReleased|=a};
 const set=(e,d)=>{c.focus();let [x,y]=pos(e);Input.x=x;Input.y=y;if(d===1){Input.pts[e.pointerId]=1;Input.down=1;Input.pressed=1;c.setPointerCapture?.(e.pointerId);let n=G.phase==='fight'&&G.enemies.some(q=>!q.dead&&Math.hypot(x-(q.x-G.camX),y-(q.y-G.camY))<110);if(e.pointerType==='mouse'||n||!(x<G.w/2&&y>65)||Input.moveId>=0){if(Input.attackId<0){Input.mouse=e.pointerType==='mouse'?1:0;Input.attackId=e.pointerId;Input.attack=1;Input.attackPressed=1;Input.aoX=Input.ax=x;Input.aoY=Input.ay=y}}else{Input.moveId=e.pointerId;Input.moX=Input.mx=x;Input.moY=Input.my=y}}else if(d===2){if(e.pointerId===Input.moveId){Input.mx=x;Input.my=y}if(e.pointerId===Input.attackId||e.pointerType==='mouse'){Input.ax=x;Input.ay=y}}else{delete Input.pts[e.pointerId];Input.down=Object.keys(Input.pts).length>0;Input.released=1;if(e.pointerId===Input.moveId)Input.moveId=-1;if(e.pointerId===Input.attackId){Input.attackId=-1;Input.attack=0;Input.attackReleased=1}try{c.releasePointerCapture?.(e.pointerId)}catch{}}e.preventDefault()};
 c.addEventListener('pointerdown',e=>set(e,1));c.addEventListener('pointermove',e=>set(e,2));c.addEventListener('pointerup',e=>set(e,0));c.addEventListener('pointercancel',e=>set(e,0));
 addEventListener('keydown',e=>{let k=e.code;Input.keys[k]=1;if(k==='KeyQ'||k==='Space')Input.black=1;if(/^Arrow|^Key[WASD]$|Space|KeyQ/.test(k))e.preventDefault()},{passive:false});addEventListener('keyup',e=>{Input.keys[e.code]=0;if(/^Arrow|^Key[WASD]$|Space|KeyQ/.test(e.code))e.preventDefault()},{passive:false});addEventListener('blur',clear);document.addEventListener?.('visibilitychange',()=>{if(document.hidden)clear()});
}
function moveIntent(){let x=0,y=0,k=Input.keys;if(k.KeyA||k.ArrowLeft)x--;if(k.KeyD||k.ArrowRight)x++;if(k.KeyW||k.ArrowUp)y--;if(k.KeyS||k.ArrowDown)y++;if(Input.moveId>=0){let dx=Input.mx-Input.moX,dy=Input.my-Input.moY,m=Math.hypot(dx,dy),q=Math.min(1,m/55);if(m>3){x+=dx/m*q;y+=dy/m*q}}let m=Math.hypot(x,y);return m>1?[x/m,y/m]:[x,y]}
function aimIntent(P){let px=P.x-G.camX,py=P.y-G.camY,dx,dy;if(Input.mouse){dx=Input.ax-px;dy=Input.ay-py}else{dx=Input.ax-Input.aoX;dy=Input.ay-Input.aoY;if(Math.hypot(dx,dy)<10){dx=Input.ax-px;dy=Input.ay-py}}let m=Math.hypot(dx,dy)||1;return[dx/m,dy/m]}
